/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_walker_demo_fmod_Voice */
#include <fmod.hpp> // FMOD的头文件，必须导入，才能使用功能

#ifndef _Included_com_walker_demo_fmod_Voice
#define _Included_com_walker_demo_fmod_Voice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_walker_demo_fmod_Voice_MODE_NORMAL
#define com_walker_demo_fmod_Voice_MODE_NORMAL 0L
#undef com_walker_demo_fmod_Voice_MODE_LUOLI
#define com_walker_demo_fmod_Voice_MODE_LUOLI 1L
#undef com_walker_demo_fmod_Voice_MODE_DASHU
#define com_walker_demo_fmod_Voice_MODE_DASHU 2L
#undef com_walker_demo_fmod_Voice_MODE_JINGSONG
#define com_walker_demo_fmod_Voice_MODE_JINGSONG 3L
#undef com_walker_demo_fmod_Voice_MODE_GAOGUAI
#define com_walker_demo_fmod_Voice_MODE_GAOGUAI 4L
#undef com_walker_demo_fmod_Voice_MODE_KONGLING
#define com_walker_demo_fmod_Voice_MODE_KONGLING 5L
/*
 * Class:     com_walker_demo_fmod_Voice
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_walker_demo_fmod_Voice_voiceChangeNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
