/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_plugintest_NativeTest */

#ifndef _Included_com_example_plugintest_NativeTest
#define _Included_com_example_plugintest_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_plugintest_NativeTest
 * Method:    getInfoFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_plugintest_NativeTest_getInfoFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
